# https://hub.docker.com/_/mysql
# Use root/example as user/password credentials

version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "recordings"

    volumes:
      - "./sql/migrations:/docker-entrypoint-initdb.d"

# (this is just an example, not intended to be a production configuration)
